-file("/usr/local/lib/erlang/lib/parsetools-2.0.10/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(riak_ql_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/riak_ql_lexer.xrl", 101).
		
-export([
	 get_tokens/1
	]).

-include("riak_ql.xrl.tests").

get_tokens(X) ->
    Toks = lex(X),
    post_process(Toks).

post_process(X) ->
    post_p(X, []).

% filter out the whitespaces at the end
post_p([], Acc) -> 
    [{Type, X} || {Type, X} <- lists:reverse(Acc), Type =/= whitespace];
% when you've merged two items hoy them back on the list
% so they can continue to sook up chars
post_p([{Word1, W1}, {Word2, W2} | T], Acc) when Word1 =:= chars   orelse
						 Word1 =:= select  orelse
						 Word1 =:= from    orelse
						 Word1 =:= limit   orelse
						 Word1 =:= and_    orelse
						 Word1 =:= or_     orelse
						 Word1 =:= delete  orelse
						 Word1 =:= drop    orelse
						 Word1 =:= groupby orelse
						 Word1 =:= merge   orelse
						 Word1 =:= inner   orelse
						 Word1 =:= join    orelse
						 Word1 =:= as,
						 Word2 =:= chars   orelse
						 Word2 =:= select  orelse
						 Word2 =:= from    orelse
						 Word2 =:= limit   orelse
						 Word2 =:= and_    orelse
						 Word2 =:= or_     orelse
						 Word2 =:= delete  orelse
						 Word2 =:= drop    orelse
						 Word2 =:= groupby orelse
						 Word2 =:= merge   orelse
						 Word2 =:= inner   orelse
						 Word2 =:= join    orelse
						 Word2 =:= as      ->
    post_p([{chars, W1 ++ W2} | T], Acc);
post_p([H | T], Acc) ->
    post_p(T, [H | Acc]).

lex(String) -> {ok, Toks, 1} = string(String),
	       Toks.

fix_up_date(Date) ->
    Date2 = string:strip(Date, both, $'), %'
    Date3 = string:strip(Date2),
    case dh_date:parse(Date3) of
	{error, bad_date} -> {chars, Date2};
	Date4             -> {datetime, Date4}
    end.
			     

strip_quoted(Date) ->
    Date2 = string:strip(Date, both, $"), %"
    string:strip(Date2).

-file("/usr/local/lib/erlang/lib/parsetools-2.0.10/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L1, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L1, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L1, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/riak_ql_lexer.erl", 340).
yystate() -> 87.

yystate(90, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line};
yystate(89, [10|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line+1, Tlen+1, 33, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(89, Ics, Line, Tlen+1, 33, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(89, Ics, Line, Tlen+1, 33, Tlen);
yystate(89, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,89};
yystate(88, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(87, [119|Ics], Line, Tlen, _, _) ->
    yystate(83, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [115|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [111|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [110|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [109|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [108|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [107|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [106|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [105|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [104|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [103|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [102|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [101|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [100|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [98|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [99|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [97|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [87|Ics], Line, Tlen, _, _) ->
    yystate(83, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [83|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [79|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [78|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [77|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [76|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [75|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [74|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [73|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [72|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [71|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [70|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [69|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [68|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [66|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [67|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [65|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [63|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [64|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [62|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [61|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [60|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [58|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [59|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [47|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [46|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [45|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [44|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [43|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [42|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [41|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [40|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [39|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [34|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [33|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [10|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line+1, Tlen+1, 33, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(89, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(89, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 38 ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 82 ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 86 ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 88, C =< 96 ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 114 ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 118 ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 120 ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(87, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,87};
yystate(86, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(90, Ics, Line, Tlen+1, Action, Alen);
yystate(86, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(90, Ics, Line, Tlen+1, Action, Alen);
yystate(86, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,86};
yystate(85, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(84, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Tlen+1, Action, Alen);
yystate(84, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,84};
yystate(83, [104|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 35, Tlen);
yystate(83, [72|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 35, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,83};
yystate(82, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Tlen+1, Action, Alen);
yystate(82, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Tlen+1, Action, Alen);
yystate(82, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,82};
yystate(81, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(80, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(79, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,79};
yystate(78, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(78, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(78, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,78};
yystate(77, [126|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 35, Tlen);
yystate(77, [61|Ics], Line, Tlen, _, _) ->
    yystate(85, Ics, Line, Tlen+1, 35, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,77};
yystate(76, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [77|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(76, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,76};
yystate(75, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(75, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,75};
yystate(74, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(74, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(74, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,74};
yystate(73, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 35 ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(73, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,73};
yystate(72, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(72, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(72, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,72};
yystate(71, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(71, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,71};
yystate(70, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(70, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,70};
yystate(69, [34|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 30, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(73, Ics, Line, Tlen+1, 30, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(73, Ics, Line, Tlen+1, 30, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 35 ->
    yystate(73, Ics, Line, Tlen+1, 30, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line,69};
yystate(68, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(67, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(66, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(65, [34|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 35, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(73, Ics, Line, Tlen+1, 35, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(73, Ics, Line, Tlen+1, 35, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 35 ->
    yystate(73, Ics, Line, Tlen+1, 35, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,65};
yystate(64, [121|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [89|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(64, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,64};
yystate(63, [101|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 35, Tlen);
yystate(63, [69|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 35, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,63};
yystate(62, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(61, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line};
yystate(60, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [66|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(59, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,59};
yystate(58, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,58};
yystate(57, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 58 ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(57, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,57};
yystate(56, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(56, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,56};
yystate(55, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,55};
yystate(54, [114|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 35, Tlen);
yystate(54, [82|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 35, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,54};
yystate(53, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(52, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(52, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,52};
yystate(51, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(51, [67|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(51, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,51};
yystate(50, [114|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 35, Tlen);
yystate(50, [101|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 35, Tlen);
yystate(50, [82|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 35, Tlen);
yystate(50, [69|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 35, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,50};
yystate(49, [45|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 35, Tlen);
yystate(49, [46|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 35, Tlen);
yystate(49, [39|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 35, Tlen);
yystate(49, [32|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 35, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 58 ->
    yystate(57, Ics, Line, Tlen+1, 35, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(57, Ics, Line, Tlen+1, 35, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(57, Ics, Line, Tlen+1, 35, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,49};
yystate(48, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(48, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,48};
yystate(47, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, [115|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 35, Tlen);
yystate(46, [110|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 35, Tlen);
yystate(46, [83|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 35, Tlen);
yystate(46, [78|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 35, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,46};
yystate(45, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(44, [114|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 35, Tlen);
yystate(44, [82|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 35, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,44};
yystate(43, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(42, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(41, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(40, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(39, [114|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 35, Tlen);
yystate(39, [82|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 35, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,39};
yystate(38, [126|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 16, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,38};
yystate(37, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(36, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(36, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,36};
yystate(35, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(34, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(33, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(32, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,32};
yystate(31, [101|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 35, Tlen);
yystate(31, [69|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 35, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,31};
yystate(30, [62|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 19, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,30};
yystate(29, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line};
yystate(28, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(28, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,28};
yystate(27, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(25, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(25, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,25};
yystate(24, [110|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 35, Tlen);
yystate(24, [78|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 35, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,24};
yystate(23, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [71|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(23, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,23};
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(22, Ics, Line, Tlen+1, 15, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,22};
yystate(21, [46|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 26, Tlen);
yystate(21, [45|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 26, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Tlen+1, 26, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,21};
yystate(20, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(19, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(19, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,19};
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,18};
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(2, Ics, Line, Tlen+1, 35, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,17};
yystate(16, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,16};
yystate(15, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(14, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(14, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,14};
yystate(13, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(12, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(12, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,12};
yystate(11, [105|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 35, Tlen);
yystate(11, [73|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 35, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,11};
yystate(10, [101|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 13, Tlen);
yystate(10, [69|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 13, Tlen);
yystate(10, [46|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 13, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Tlen+1, 13, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,10};
yystate(9, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(9, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,9};
yystate(8, [111|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 35, Tlen);
yystate(8, [79|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 35, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,8};
yystate(7, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [77|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(7, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,7};
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(6, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,6};
yystate(5, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(3, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,3};
yystate(2, [101|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 14, Tlen);
yystate(2, [69|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 14, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(2, Ics, Line, Tlen+1, 14, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,2};
yystate(1, [10|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line+1, Tlen+1, 28, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(5, Ics, Line, Tlen+1, 28, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 46 ->
    yystate(5, Ics, Line, Tlen+1, 28, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(5, Ics, Line, Tlen+1, 28, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,1};
yystate(0, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars);
yyaction(1, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars);
yyaction(2, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars);
yyaction(3, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars);
yyaction(4, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars);
yyaction(5, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars);
yyaction(6, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars);
yyaction(7, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars);
yyaction(8, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars);
yyaction(9, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars);
yyaction(10, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars);
yyaction(11, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars);
yyaction(12, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars);
yyaction(13, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars);
yyaction(14, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars);
yyaction(15, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars);
yyaction(16, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars);
yyaction(17, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars);
yyaction(18, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars);
yyaction(19, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars);
yyaction(20, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars);
yyaction(21, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_21(TokenChars);
yyaction(22, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars);
yyaction(23, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars);
yyaction(24, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars);
yyaction(25, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_25(TokenChars);
yyaction(26, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars);
yyaction(27, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_27(TokenChars);
yyaction(28, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_28(TokenChars);
yyaction(29, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_29(TokenChars);
yyaction(30, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_30(TokenChars);
yyaction(31, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_31(TokenChars);
yyaction(32, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_32(TokenChars);
yyaction(33, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_33(TokenChars);
yyaction(34, _, _, _) ->
    yyaction_34();
yyaction(35, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_35(TokenChars);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("src/riak_ql_lexer.xrl", 51).
yyaction_0(TokenChars) ->
     { token, { select, TokenChars } } .

-compile({inline,yyaction_1/1}).
-file("src/riak_ql_lexer.xrl", 52).
yyaction_1(TokenChars) ->
     { token, { from, TokenChars } } .

-compile({inline,yyaction_2/1}).
-file("src/riak_ql_lexer.xrl", 53).
yyaction_2(TokenChars) ->
     { token, { limit, TokenChars } } .

-compile({inline,yyaction_3/1}).
-file("src/riak_ql_lexer.xrl", 54).
yyaction_3(TokenChars) ->
     { token, { where, TokenChars } } .

-compile({inline,yyaction_4/1}).
-file("src/riak_ql_lexer.xrl", 55).
yyaction_4(TokenChars) ->
     { token, { and_, TokenChars } } .

-compile({inline,yyaction_5/1}).
-file("src/riak_ql_lexer.xrl", 56).
yyaction_5(TokenChars) ->
     { token, { or_, TokenChars } } .

-compile({inline,yyaction_6/1}).
-file("src/riak_ql_lexer.xrl", 57).
yyaction_6(TokenChars) ->
     { token, { delete, TokenChars } } .

-compile({inline,yyaction_7/1}).
-file("src/riak_ql_lexer.xrl", 58).
yyaction_7(TokenChars) ->
     { token, { drop, TokenChars } } .

-compile({inline,yyaction_8/1}).
-file("src/riak_ql_lexer.xrl", 59).
yyaction_8(TokenChars) ->
     { token, { groupby, TokenChars } } .

-compile({inline,yyaction_9/1}).
-file("src/riak_ql_lexer.xrl", 60).
yyaction_9(TokenChars) ->
     { token, { merge, TokenChars } } .

-compile({inline,yyaction_10/1}).
-file("src/riak_ql_lexer.xrl", 61).
yyaction_10(TokenChars) ->
     { token, { inner, TokenChars } } .

-compile({inline,yyaction_11/1}).
-file("src/riak_ql_lexer.xrl", 62).
yyaction_11(TokenChars) ->
     { token, { join, TokenChars } } .

-compile({inline,yyaction_12/1}).
-file("src/riak_ql_lexer.xrl", 63).
yyaction_12(TokenChars) ->
     { token, { as, TokenChars } } .

-compile({inline,yyaction_13/1}).
-file("src/riak_ql_lexer.xrl", 65).
yyaction_13(TokenChars) ->
     { token, { int, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_14/1}).
-file("src/riak_ql_lexer.xrl", 66).
yyaction_14(TokenChars) ->
     { token, { float, list_to_float (TokenChars) } } .

-compile({inline,yyaction_15/1}).
-file("src/riak_ql_lexer.xrl", 67).
yyaction_15(TokenChars) ->
     { token, { float, list_to_float (TokenChars) } } .

-compile({inline,yyaction_16/1}).
-file("src/riak_ql_lexer.xrl", 69).
yyaction_16(TokenChars) ->
     { token, { eq, TokenChars } } .

-compile({inline,yyaction_17/1}).
-file("src/riak_ql_lexer.xrl", 70).
yyaction_17(TokenChars) ->
     { token, { approx, TokenChars } } .

-compile({inline,yyaction_18/1}).
-file("src/riak_ql_lexer.xrl", 71).
yyaction_18(TokenChars) ->
     { token, { gt, TokenChars } } .

-compile({inline,yyaction_19/1}).
-file("src/riak_ql_lexer.xrl", 72).
yyaction_19(TokenChars) ->
     { token, { lt, TokenChars } } .

-compile({inline,yyaction_20/1}).
-file("src/riak_ql_lexer.xrl", 73).
yyaction_20(TokenChars) ->
     { token, { ne, TokenChars } } .

-compile({inline,yyaction_21/1}).
-file("src/riak_ql_lexer.xrl", 74).
yyaction_21(TokenChars) ->
     { token, { nomatch, TokenChars } } .

-compile({inline,yyaction_22/1}).
-file("src/riak_ql_lexer.xrl", 75).
yyaction_22(TokenChars) ->
     { token, { notapprox, TokenChars } } .

-compile({inline,yyaction_23/1}).
-file("src/riak_ql_lexer.xrl", 77).
yyaction_23(TokenChars) ->
     { token, { openb, TokenChars } } .

-compile({inline,yyaction_24/1}).
-file("src/riak_ql_lexer.xrl", 78).
yyaction_24(TokenChars) ->
     { token, { closeb, TokenChars } } .

-compile({inline,yyaction_25/1}).
-file("src/riak_ql_lexer.xrl", 80).
yyaction_25(TokenChars) ->
     { token, { plus, TokenChars } } .

-compile({inline,yyaction_26/1}).
-file("src/riak_ql_lexer.xrl", 81).
yyaction_26(TokenChars) ->
     { token, { minus, TokenChars } } .

-compile({inline,yyaction_27/1}).
-file("src/riak_ql_lexer.xrl", 82).
yyaction_27(TokenChars) ->
     { token, { maybetimes, TokenChars } } .

-compile({inline,yyaction_28/1}).
-file("src/riak_ql_lexer.xrl", 83).
yyaction_28(TokenChars) ->
     { token, { div_, TokenChars } } .

-compile({inline,yyaction_29/1}).
-file("src/riak_ql_lexer.xrl", 85).
yyaction_29(TokenChars) ->
     { token, fix_up_date (TokenChars) } .

-compile({inline,yyaction_30/1}).
-file("src/riak_ql_lexer.xrl", 87).
yyaction_30(TokenChars) ->
     { token, { quoted, strip_quoted (TokenChars) } } .

-compile({inline,yyaction_31/1}).
-file("src/riak_ql_lexer.xrl", 89).
yyaction_31(TokenChars) ->
     { token, { regex, TokenChars } } .

-compile({inline,yyaction_32/1}).
-file("src/riak_ql_lexer.xrl", 91).
yyaction_32(TokenChars) ->
     { token, { comma, TokenChars } } .

-compile({inline,yyaction_33/1}).
-file("src/riak_ql_lexer.xrl", 93).
yyaction_33(TokenChars) ->
     { token, { whitespace, TokenChars } } .

-compile({inline,yyaction_34/0}).
-file("src/riak_ql_lexer.xrl", 95).
yyaction_34() ->
     { end_token, { '$end' } } .

-compile({inline,yyaction_35/1}).
-file("src/riak_ql_lexer.xrl", 97).
yyaction_35(TokenChars) ->
     { token, { chars, TokenChars } } .

-file("/usr/local/lib/erlang/lib/parsetools-2.0.10/include/leexinc.hrl", 282).
