-file("/usr/local/lib/erlang/lib/parsetools-2.0.10/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(riak_ql).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/riak_ql.xrl", 86).

-include_lib("eunit/include/eunit.hrl").

-export([
         lex/1
        ]).

-compile(export_all).

lex(String) -> {ok, Toks, 1} = string(String),
               Toks.

strip_date(Date) ->
    Date2 = string:strip(Date, both, $'), %'
    Date3 = string:strip(Date2),
    dh_date:parse(Date3).

strip_quoted(Date) ->
    Date2 = string:strip(Date, both, $"), %"
    string:strip(Date2).

-file("/usr/local/lib/erlang/lib/parsetools-2.0.10/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L1, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L1, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L1, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/riak_tsql.erl", 298).
yystate() -> 82.

yystate(85, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(84, [10|Ics], Line, Tlen, _, _) ->
    yystate(84, Ics, Line+1, Tlen+1, 27, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(84, Ics, Line, Tlen+1, 27, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(84, Ics, Line, Tlen+1, 27, Tlen);
yystate(84, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,84};
yystate(83, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(82, [126|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [115|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [111|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [110|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [109|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [108|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [107|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [106|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [105|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [104|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [103|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [102|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [101|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [100|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [98|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [99|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [97|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [87|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [83|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [79|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [78|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [77|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [76|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [75|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [74|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [73|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [72|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [71|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [70|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [69|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [68|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [66|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [67|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [65|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [63|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [64|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [62|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [61|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [60|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [58|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [59|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [47|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [45|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [41|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [40|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [39|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [34|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [33|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [10|Ics], Line, Tlen, _, _) ->
    yystate(84, Ics, Line+1, Tlen+1, 27, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(84, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(84, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 38 ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 42, C =< 44 ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(4, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 82 ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 86 ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 88, C =< 96 ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 114 ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 125 ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,82};
yystate(81, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(81, [77|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(81, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,81};
yystate(80, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(79, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,79};
yystate(78, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(77, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(77, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,77};
yystate(76, [61|Ics], Line, Tlen, _, _) ->
    yystate(80, Ics, Line, Tlen+1, 29, Tlen);
yystate(76, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,76};
yystate(75, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line};
yystate(74, [101|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 29, Tlen);
yystate(74, [69|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 29, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,74};
yystate(73, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(72, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(72, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(72, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(72, [C|Ics], Line, Tlen, Action, Alen) when C >= 35 ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(72, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,72};
yystate(71, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(71, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,71};
yystate(70, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(70, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,70};
yystate(69, [121|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [89|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(69, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,69};
yystate(68, [34|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 25, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(72, Ics, Line, Tlen+1, 25, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(72, Ics, Line, Tlen+1, 25, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 35 ->
    yystate(72, Ics, Line, Tlen+1, 25, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,68};
yystate(67, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(67, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(67, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,67};
yystate(66, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(66, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,66};
yystate(65, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [66|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(65, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,65};
yystate(64, [34|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 29, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(72, Ics, Line, Tlen+1, 29, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(72, Ics, Line, Tlen+1, 29, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 35 ->
    yystate(72, Ics, Line, Tlen+1, 29, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,64};
yystate(63, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(63, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,63};
yystate(62, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [67|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(62, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,62};
yystate(61, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(61, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,61};
yystate(60, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(59, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(59, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,59};
yystate(58, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,58};
yystate(57, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(57, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,57};
yystate(56, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 58 ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(56, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,56};
yystate(55, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,55};
yystate(54, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(53, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(53, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,53};
yystate(52, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(51, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(50, [114|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 29, Tlen);
yystate(50, [82|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 29, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,50};
yystate(49, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(48, [45|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 29, Tlen);
yystate(48, [39|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 29, Tlen);
yystate(48, [32|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 29, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 58 ->
    yystate(56, Ics, Line, Tlen+1, 29, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(56, Ics, Line, Tlen+1, 29, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(56, Ics, Line, Tlen+1, 29, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,48};
yystate(47, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(46, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(45, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,45};
yystate(44, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(43, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(43, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,43};
yystate(42, [101|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 29, Tlen);
yystate(42, [69|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 29, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,42};
yystate(41, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,41};
yystate(40, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(39, [114|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 29, Tlen);
yystate(39, [82|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 29, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,39};
yystate(38, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(38, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,38};
yystate(37, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(37, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,37};
yystate(36, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(36, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,36};
yystate(35, [114|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 29, Tlen);
yystate(35, [82|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 29, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,35};
yystate(34, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [71|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,34};
yystate(33, [104|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 29, Tlen);
yystate(33, [72|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 29, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,33};
yystate(32, [46|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 29, Tlen);
yystate(32, [45|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 29, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(4, Ics, Line, Tlen+1, 29, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,32};
yystate(31, [114|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 29, Tlen);
yystate(31, [101|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 29, Tlen);
yystate(31, [82|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 29, Tlen);
yystate(31, [69|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 29, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,31};
yystate(30, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(30, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,30};
yystate(29, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(12, Ics, Line, Tlen+1, 29, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,28};
yystate(27, [115|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 29, Tlen);
yystate(27, [110|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 29, Tlen);
yystate(27, [83|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 29, Tlen);
yystate(27, [78|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 29, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,27};
yystate(26, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(25, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(25, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,25};
yystate(24, [47|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 26, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(20, Ics, Line, Tlen+1, 26, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 46 ->
    yystate(20, Ics, Line, Tlen+1, 26, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(20, Ics, Line, Tlen+1, 26, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,24};
yystate(23, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(22, [105|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 29, Tlen);
yystate(22, [73|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 29, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,22};
yystate(21, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,21};
yystate(20, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 46 ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 48 ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,20};
yystate(19, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(18, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [77|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,18};
yystate(17, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(17, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(17, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,17};
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(20, Ics, Line, Tlen+1, 29, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 11 ->
    yystate(20, Ics, Line, Tlen+1, 29, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,16};
yystate(15, [62|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 19, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,15};
yystate(14, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(14, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,14};
yystate(13, [110|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 29, Tlen);
yystate(13, [78|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 29, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,13};
yystate(12, [101|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 14, Tlen);
yystate(12, [69|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 14, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(12, Ics, Line, Tlen+1, 14, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,12};
yystate(11, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(10, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(10, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,10};
yystate(9, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(8, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,8};
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(7, Ics, Line, Tlen+1, 15, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,7};
yystate(6, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(5, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, [101|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 13, Tlen);
yystate(4, [69|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 13, Tlen);
yystate(4, [46|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 13, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(4, Ics, Line, Tlen+1, 13, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,4};
yystate(3, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,3};
yystate(2, [111|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 29, Tlen);
yystate(2, [79|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 29, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,2};
yystate(1, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(1, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,1};
yystate(0, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars);
yyaction(1, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars);
yyaction(2, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars);
yyaction(3, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars);
yyaction(4, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars);
yyaction(5, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars);
yyaction(6, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars);
yyaction(7, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars);
yyaction(8, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars);
yyaction(9, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars);
yyaction(10, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars);
yyaction(11, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars);
yyaction(12, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars);
yyaction(13, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars);
yyaction(14, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars);
yyaction(15, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars);
yyaction(16, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars);
yyaction(17, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars);
yyaction(18, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars);
yyaction(19, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars);
yyaction(20, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars);
yyaction(21, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_21(TokenChars);
yyaction(22, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars);
yyaction(23, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars);
yyaction(24, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars);
yyaction(25, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_25(TokenChars);
yyaction(26, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars);
yyaction(27, _, _, _) ->
    yyaction_27();
yyaction(28, _, _, _) ->
    yyaction_28();
yyaction(29, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_29(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("src/riak_tsql.xrl", 43).
yyaction_0(TokenChars) ->
     { token, { select, TokenChars } } .

-compile({inline,yyaction_1/1}).
-file("src/riak_tsql.xrl", 44).
yyaction_1(TokenChars) ->
     { token, { from, TokenChars } } .

-compile({inline,yyaction_2/1}).
-file("src/riak_tsql.xrl", 45).
yyaction_2(TokenChars) ->
     { token, { limit, TokenChars } } .

-compile({inline,yyaction_3/1}).
-file("src/riak_tsql.xrl", 46).
yyaction_3(TokenChars) ->
     { token, { where, TokenChars } } .

-compile({inline,yyaction_4/1}).
-file("src/riak_tsql.xrl", 47).
yyaction_4(TokenChars) ->
     { token, { and_, TokenChars } } .

-compile({inline,yyaction_5/1}).
-file("src/riak_tsql.xrl", 48).
yyaction_5(TokenChars) ->
     { token, { or_, TokenChars } } .

-compile({inline,yyaction_6/1}).
-file("src/riak_tsql.xrl", 49).
yyaction_6(TokenChars) ->
     { token, { delete, TokenChars } } .

-compile({inline,yyaction_7/1}).
-file("src/riak_tsql.xrl", 50).
yyaction_7(TokenChars) ->
     { token, { drop, TokenChars } } .

-compile({inline,yyaction_8/1}).
-file("src/riak_tsql.xrl", 51).
yyaction_8(TokenChars) ->
     { token, { groupby, TokenChars } } .

-compile({inline,yyaction_9/1}).
-file("src/riak_tsql.xrl", 52).
yyaction_9(TokenChars) ->
     { token, { merge, TokenChars } } .

-compile({inline,yyaction_10/1}).
-file("src/riak_tsql.xrl", 53).
yyaction_10(TokenChars) ->
     { token, { inner, TokenChars } } .

-compile({inline,yyaction_11/1}).
-file("src/riak_tsql.xrl", 54).
yyaction_11(TokenChars) ->
     { token, { join, TokenChars } } .

-compile({inline,yyaction_12/1}).
-file("src/riak_tsql.xrl", 55).
yyaction_12(TokenChars) ->
     { token, { as, TokenChars } } .

-compile({inline,yyaction_13/1}).
-file("src/riak_tsql.xrl", 57).
yyaction_13(TokenChars) ->
     { token, { int, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_14/1}).
-file("src/riak_tsql.xrl", 58).
yyaction_14(TokenChars) ->
     { token, { float, list_to_float (TokenChars) } } .

-compile({inline,yyaction_15/1}).
-file("src/riak_tsql.xrl", 59).
yyaction_15(TokenChars) ->
     { token, { float, list_to_float (TokenChars) } } .

-compile({inline,yyaction_16/1}).
-file("src/riak_tsql.xrl", 61).
yyaction_16(TokenChars) ->
     { token, { { maybeop, eq }, TokenChars } } .

-compile({inline,yyaction_17/1}).
-file("src/riak_tsql.xrl", 62).
yyaction_17(TokenChars) ->
     { token, { { maybeop, approxmatch }, TokenChars } } .

-compile({inline,yyaction_18/1}).
-file("src/riak_tsql.xrl", 64).
yyaction_18(TokenChars) ->
     { token, { { op, gt }, TokenChars } } .

-compile({inline,yyaction_19/1}).
-file("src/riak_tsql.xrl", 65).
yyaction_19(TokenChars) ->
     { token, { { op, lt }, TokenChars } } .

-compile({inline,yyaction_20/1}).
-file("src/riak_tsql.xrl", 66).
yyaction_20(TokenChars) ->
     { token, { { op, ne }, TokenChars } } .

-compile({inline,yyaction_21/1}).
-file("src/riak_tsql.xrl", 67).
yyaction_21(TokenChars) ->
     { token, { { op, nomatch }, TokenChars } } .

-compile({inline,yyaction_22/1}).
-file("src/riak_tsql.xrl", 69).
yyaction_22(TokenChars) ->
     { token, { { brackets, open }, TokenChars } } .

-compile({inline,yyaction_23/1}).
-file("src/riak_tsql.xrl", 70).
yyaction_23(TokenChars) ->
     { token, { { brackets, close }, TokenChars } } .

-compile({inline,yyaction_24/1}).
-file("src/riak_tsql.xrl", 72).
yyaction_24(TokenChars) ->
     { token, { datetime, strip_date (TokenChars) } } .

-compile({inline,yyaction_25/1}).
-file("src/riak_tsql.xrl", 74).
yyaction_25(TokenChars) ->
     { token, { quoted, strip_quoted (TokenChars) } } .

-compile({inline,yyaction_26/1}).
-file("src/riak_tsql.xrl", 76).
yyaction_26(TokenChars) ->
     { token, { reqex, TokenChars } } .

-compile({inline,yyaction_27/0}).
-file("src/riak_tsql.xrl", 78).
yyaction_27() ->
     skip_token .

-compile({inline,yyaction_28/0}).
-file("src/riak_tsql.xrl", 80).
yyaction_28() ->
     { end_token, { '$end' } } .

-compile({inline,yyaction_29/2}).
-file("src/riak_tsql.xrl", 82).
yyaction_29(TokenChars, TokenLine) ->
     { token, { char, TokenLine, TokenChars } } .

-file("/usr/local/lib/erlang/lib/parsetools-2.0.10/include/leexinc.hrl", 282).
